### PR TITLE
Check socrata types when converting bools to strings

### PR DESCRIPTION
**Pull request by johnclary**
Towards fixing https://github.com/cityofaustin/atd-data-tech/issues/9985

Our Socrata datasets have been been created with type mismatch b/t Knack and Socrata, where a boolean field in Knack is configured as a text field in Socrata. 

Rather than retroactively fixing those poorly configured datasets, we have continued to use text fields in Socrata where booleans should be used, and our `records_to_socrata` script would convert any and all booleans in the Knack payload to strings.

This PR updates the `bools_to_string` function to selectively convert bools to strings based on the column type in Socrata. It is backwards compatible, and going forward we can configure Socrata datasets with actual boolean types.

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
Looks good to me - thanks for adding that! I've read your code closely, and it makes sense, but I have not spun it up. I think it's good to ship though, for sure.

**Review by mddilley — APPROVED** [review]
This makes sense to me and looks safe for new and old datasets. Thanks for the extra docs here and the refresher earlier! 📺

**Review by Charlie-Henry — APPROVED** [review]
Thanks for showing us the Knack scripts today! I'll just leave these [Socrata docs](https://support.socrata.com/hc/en-us/articles/360024040594-Dataset-Validation-for-Column-Data-Type-Values) that show that Socrata is expecting a non-capitalized boolean `true` or `false`. 

I haven't tested, but it looks like `str(v)` was causing it to be stored as capitalized `True` or `False`.

**Review by chiaberry — APPROVED** [review]

**Comment by johnclary** [comment]
Thanks y'all! I just added more detail to the section of the docs about dealing with schema changes. Happy to open a separate PR with still more detail. Lmk if anything jumps out at you.

@Charlie-Henry yep, you're right that `str(v)` was causing the caps issue, and, to boot, even the string`"false"` was failing. Socrata will not cooerce strings to bools, you have to give it a proper JSON bool:
 ```json
{"my_field": false}
```

**Pull request merged**
