### PR TITLE
Add header to a few scripts 

### PR DESCRIPTION
**Pull request by johnclary**
While working on https://github.com/cityofaustin/atd-data-tech/issues/12860, I ran into Docker errors trying to get these scripts to work.

These have only been running normally on Prefect, so I guess the way Prefect invokes docker is somehow different from Airflow.

### CODE REVIEW

**Review by frankhereford — APPROVED** [review]
thanks for adding the shebang lines! 🚢 🚢

**Review by mddilley — APPROVED** [review]
🚢 🙏

**Review by chiaberry — APPROVED** [review]

**Review by Charlie-Henry — APPROVED** [review]
Did not know these served a purpose!

**Comment by johnclary** [comment]
thanks y'all! we'll see if this cures what ails me...

**Pull request merged**
