### PR TITLE
Rework Dockerfile for build compatibility on ARM, Intel

### PR DESCRIPTION
**Pull request by frankhereford**
This PR intends to address https://github.com/cityofaustin/atd-data-tech/issues/16553.

It reworks the Dockerfile to:

* Build natively on Intel, ARM
* Build under `buildx` for the same platforms
* Use an updated version of python
* Remove unneeded build steps

### Consideration

I have only tested that the image builds, and I have not tested that anything in the repo runs on it. I'll be realllly surprised if there's any snag, but I did want to say that. FWIW, both `python` and `python3` are in the path, so it should be a drop in replacement.

### Testing

Not sure exactly, but if it works for what you're working on, that feels pretty promising. 🙏 

### Correction

 I said in slack that `slim` was a debian release, and that was wrong. Here, we're using `FROM python:3.12-slim-bookworm` now, where slim designates a minimal docker image and bookworm designates the current stable debian release.

### CODE REVIEW

**Review by Charlie-Henry — COMMENTED** [review]
TY Frank! I tested one of our airflow DAGs with this and one small change needs to be made. The starting directory for the OG container is `atd-knack-services/`. So, to make it compatible with our airflow commands, I found this worked:

```
FROM python:3.12-slim-bookworm
RUN apt-get update && apt-get install -y build-essential
COPY . /app/atd-knack-services
WORKDIR /app
RUN find /app -type f -name "*.py" -exec chmod +x {} \;
RUN pip install -r /app/atd-knack-services/requirements_production.txt
```

**Comment by frankhereford** [comment]
@Charlie-Henry wrote:

> So, to make it compatible with our airflow commands, I found this worked

So helpful! Thank you Charlie. I adopted your suggestion 100%.

**Review by Charlie-Henry — APPROVED** [review]
💯 ty Frank!

**Comment by Charlie-Henry** [comment]
@frankhereford, I noticed that I can't pull the image from dockerhub 

> $ docker pull atddocker/atd-knack-services:production
> production: Pulling from atddocker/atd-knack-services
> no matching manifest for linux/arm64/v8 in the manifest list entries

but if I add `--platform linux/x86_64/v8`, it works fine sooo I don't think this is a big deal
> $ docker pull --platform linux/x86_64/v8 atddocker/atd-knack-services:production

**Comment by frankhereford** [comment]
@Charlie-Henry wrote:

> I noticed that I can't pull the image from dockerhub

Thanks for the observation Charlie! I created an issue to fix this and put it on the docket for our next refinement meeting. 🙏

**Pull request merged**
